import { Card } from "@/components/ui/Card";
import { RiskMatrix } from "@/components/report/RiskMatrix";
import type { Report } from "@/lib/types/database";

interface ReportViewerProps {
  report: Report;
}

export function ReportViewer({ report }: ReportViewerProps) {
  const contentEn = report.content_en as Record<string, string>;
  const contentTh = report.content_th as Record<string, string>;

  return (
    <div className="max-w-5xl mx-auto space-y-12">
      {/* Document Cover */}
      <div className="text-center py-16 border-b border-outline-variant/20">
        <p className="text-[10px] uppercase tracking-[0.3em] text-tertiary font-semibold mb-4">
          {report.classification}
        </p>
        <h1 className="font-headline text-6xl md:text-7xl font-extrabold text-on-surface leading-tight mb-6">
          {report.title}
        </h1>
        <div className="flex items-center justify-center gap-6 text-sm text-on-surface-variant">
          <span>Type: {report.report_type}</span>
          <span>
            Generated: {new Date(report.created_at).toLocaleDateString()}
          </span>
        </div>
      </div>

      {/* Executive Summary - dual language */}
      <section>
        <h2 className="font-headline text-2xl font-bold text-on-surface mb-6">
          Executive Summary
        </h2>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card variant="low">
            <p className="text-[10px] uppercase tracking-widest text-primary font-semibold mb-3">
              English
            </p>
            <div className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-wrap">
              {contentEn?.executive_summary ??
                "Executive summary not available."}
            </div>
          </Card>
          <Card variant="default">
            <p className="text-[10px] uppercase tracking-widest text-secondary font-semibold mb-3">
              Thai
            </p>
            <div className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-wrap thai-text">
              {contentTh?.executive_summary ??
                "ไม่มีสรุปสำหรับผู้บริหาร"}
            </div>
          </Card>
        </div>
      </section>

      {/* Risk Matrix */}
      <section>
        <h2 className="font-headline text-2xl font-bold text-on-surface mb-6">
          Risk Assessment Matrix
        </h2>
        <Card variant="low">
          <RiskMatrix currentThreat={{ likelihood: 2, impact: 3 }} />
        </Card>
      </section>

      {/* Recommended Actions */}
      <section>
        <h2 className="font-headline text-2xl font-bold text-on-surface mb-6">
          Recommended Actions
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card variant="low">
            <h3 className="text-[10px] uppercase tracking-widest text-error font-semibold mb-4">
              Immediate (0-12H)
            </h3>
            <div className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-wrap">
              {contentEn?.immediate_actions ??
                "No immediate actions specified."}
            </div>
          </Card>
          <Card variant="low">
            <h3 className="text-[10px] uppercase tracking-widest text-primary font-semibold mb-4">
              Strategic (48H+)
            </h3>
            <div className="text-sm text-on-surface-variant leading-relaxed whitespace-pre-wrap">
              {contentEn?.strategic_actions ??
                "No strategic actions specified."}
            </div>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-outline-variant/20 pt-6 pb-8 text-center">
        <p className="text-[10px] uppercase tracking-[0.3em] text-tertiary font-semibold">
          {report.classification}
        </p>
        <p className="text-xs text-on-surface-variant mt-2">
          This report was generated by Sentinel Lens AI and should be reviewed
          by qualified analysts before distribution.
        </p>
      </footer>
    </div>
  );
}
